### ISSUE TITLE
Image from opencv

### ISSUE THREAD

**Issue by kalmastenitin** [cetra3/mtcnn#5]
Hi! 
This is nice implementation. Can we use this use with opencv frame as input instead of image as input? It might helpful in creating pipeline of face detection

**Comment by cetra3** [comment]
Yes you should be able to use an opencv frame, but will need to flatten the pixels into BGR data as per what's done here:

https://github.com/cetra3/mtcnn/blob/59783c80b73ec0e3eb2f66f2c2062d5d3ba746c0/src/main.rs#L48-L56
